# Generated by Django 2.0.5 on 2018-07-11 19:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30, verbose_name='Кличка')),
                ('Age', models.PositiveSmallIntegerField(default=0, verbose_name='Возраст')),
                ('Breed', models.CharField(max_length=50, verbose_name='Порода')),
                ('Hairiness', models.CharField(max_length=50, verbose_name='Волосатость')),
                ('Created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('Changed', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Хозяин')),
            ],
            options={
                'verbose_name': 'Кот',
                'verbose_name_plural': 'Коты',
            },
        ),
    ]
